theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
plugins_dir: _plugins
baseurl: /4d-plugin-draft-email

title: "4d-plugin-draft-email"
description: "Draft an HTML email with attachments, ready to edit or send in Mail app."
logo: "/assets/logo.png"   # optional
show_downloads: true       # controls the download links in header
github:
  is_user_page: true
  owner_url: "https://github.com/miyako"
  repository_url: "https://github.com/miyako/4d-plugin-draft-email"
  is_project_page: false

exclude:
  - "vendor"
  - "resources"
  - "LICENSE"
  - "README.md"
  - "Gemfile"
